In [1]:
"""Module import"""

"""Import module of openalea packages"""
from openalea.core import path
from openalea.mtg import *
from openalea.mtg.algo import orders
from openalea.deploy.shared_data import shared_data
import openalea.plantgl.all as pgl

""" Import module of strawberry packages"""
import openalea.strawberry
from openalea.strawberry import Rules_production
from openalea.strawberry import Visualization

""" import module R"""
#from rpy2 import *

NOT using graph editor observer No module named grapheditor

' import module R'

In [2]:
% gui qt
files = shared_data(openalea.strawberry).glob('*.mtg')
#files

ERROR:tornado.application:Exception in callback <functools.partial object at 0x0000000007264E58>
Traceback (most recent call last):
  File "C:\Users\mlabadie\AppData\Local\Continuum\miniconda2\envs\strawberry\lib\site-packages\tornado\ioloop.py", line 759, in _run_callback
    ret = callback()
  File "C:\Users\mlabadie\AppData\Local\Continuum\miniconda2\envs\strawberry\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\mlabadie\AppData\Local\Continuum\miniconda2\envs\strawberry\lib\site-packages\ipykernel\kernelbase.py", line 263, in enter_eventloop
    self.eventloop(self)
  File "C:\Users\mlabadie\AppData\Local\Continuum\miniconda2\envs\strawberry\lib\site-packages\ipykernel\eventloops.py", line 134, in loop_qt5
    return loop_qt4(kernel)
  File "C:\Users\mlabadie\AppData\Local\Continuum\miniconda2\envs\strawberry\lib\site-packages\ipykernel\eventloops.py", line 116, in loop_qt4
    kernel.app = get_app_qt4([" "])
  File "C:\Users\mlabadie\AppData\Local\Continuum\miniconda2\envs\strawberry\lib\site-packages\IPython\lib\guisupport.py", line 114, in get_app_qt4
    from IPython.external.qt_for_kernel import QtGui
  File "C:\Users\mlabadie\AppData\Local\Continuum\miniconda2\envs\strawberry\lib\site-packages\IPython\external\qt_for_kernel.py", line 95, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "C:\Users\mlabadie\AppData\Local\Continuum\miniconda2\envs\strawberry\lib\site-packages\IPython\external\qt_loaders.py", line 372, in load_qt
    api_options))
ImportError:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:                              None
    PyQt4 available (requires QtCore, QtGui, QtSvg):            True
    PyQt5 available (requires QtCore, QtGui, QtSvg, QtWidgets): False
    PySide >= 1.0.3 installed:                                  False
    PySide2 installed:                                          False
    Tried to load:                                              ['pyqt5']

In [10]:
g=MTG(files[16]) 
files[16]

replace all the date format by -

Path(u'c:\\users\\mlabadie\\appdata\\local\\continuum\\miniconda2\\envs\\strawberry\\lib\\site-packages\\openalea.strawberry-1.0.0-py2.7.egg\\share\\data\\Nils_New.mtg')

In [11]:
#visualisation by Genotype and date
#g=MTG(files[6]) 
g.properties()['order'] = orders(g)
Rules_production.color_code(g)
scene = Visualization.visualise_plants(g)

pgl.Viewer.display(scene)

In [14]:
""" Merge all MTG to realize au big_MTG with all varieties"""

big_mtg = MTG()
for fn in files:
    big_mtg = algo.union(big_mtg, MTG(fn))
g = big_mtg
genotypes = set(g.property("Genotype").itervalues())
print genotypes

replace all the date format by -
replace all the date format by -
replace all the date format by -
replace all the date format by -
replace all the date format by -
replace all the date format by -

KeyError: 'YYYY/MM/DD'

In [15]:
""" Import dataframe"""
from openalea.strawberry import analysis
g.properties()['order'] = orders(g)
Rules_production.color_code(g)
df = analysis.to_dataframe(g, g.vertices(scale=1))
df

,Architectural_date,Genotype,Plant_ID,_line,complex,index,label,order,parent,scale,vid
1,10/12/2014,Gariguette,1,60,0,1,P,0,None,1,1
73,10/12/2014,Gariguette,2,133,0,73,P,0,None,1,73
146,10/12/2014,Gariguette,3,207,0,146,P,0,None,1,146
263,10/12/2014,Gariguette,4,325,0,263,P,0,None,1,263
326,10/12/2014,Gariguette,5,389,0,326,P,0,None,1,326
382,10/12/2014,Gariguette,6,446,0,382,P,0,None,1,382
444,10/12/2014,Gariguette,7,509,0,444,P,0,None,1,444
504,10/12/2014,Gariguette,8,570,0,504,P,0,None,1,504
561,10/12/2014,Gariguette,9,628,0,561,P,0,None,1,561
635,08/01/2015,Gariguette,1,703,0,635,P,0,None,1,635
816,08/01/2015,Gariguette,2,885,0,816,P,0,None,1,816
913,08/01/2015,Gariguette,3,983,0,913,P,0,None,1,913
1050,08/01/2015,Gariguette,4,1121,0,1050,P,0,None,1,1050
1201,08/01/2015,Gariguette,5,1273,0,1201,P,0,None,1,1201
1321,08/01/2015,Gariguette,6,1394,0,1321,P,0,None,1,1321
1426,08/01/2015,Gariguette,7,1500,0,1426,P,0,None,1,1426
1533,08/01/2015,Gariguette,8,1608,0,1533,P,0,None,1,1533
1620,08/01/2015,Gariguette,9,1696,0,1620,P,0,None,1,1620
1709,12/02/2015,Gariguette,1,1786,0,1709,P,0,None,1,1709
1947,12/02/2015,Gariguette,2,2025,0,1947,P,0,None,1,1947
2067,12/02/2015,Gariguette,3,2146,0,2067,P,0,None,1,2067
2167,12/02/2015,Gariguette,4,2247,0,2167,P,0,None,1,2167
2238,12/02/2015,Gariguette,5,2319,0,2238,P,0,None,1,2238
2441,12/02/2015,Gariguette,6,2523,0,2441,P,0,None,1,2441
2603,12/02/2015,Gariguette,7,2686,0,2603,P,0,None,1,2603
2678,12/02/2015,Gariguette,8,2762,0,2678,P,0,None,1,2678
2790,12/02/2015,Gariguette,9,2875,0,2790,P,0,None,1,2790
2896,06/03/2015,Gariguette,1,2982,0,2896,P,0,None,1,2896
2987,06/03/2015,Gariguette,2,3074,0,2987,P,0,None,1,2987
3075,06/03/2015,Gariguette,3,3163,0,3075,P,0,None,1,3075
3194,06/03/2015,Gariguette,4,3283,0,3194,P,0,None,1,3194
3324,06/03/2015,Gariguette,5,3414,0,3324,P,0,None,1,3324
3441,06/03/2015,Gariguette,6,3532,0,3441,P,0,None,1,3441
3553,06/03/2015,Gariguette,7,3645,0,3553,P,0,None,1,3553
3627,06/03/2015,Gariguette,8,3720,0,3627,P,0,None,1,3627
3732,06/03/2015,Gariguette,9,3826,0,3732,P,0,None,1,3732
3879,02/04/2015,Gariguette,1,3974,0,3879,P,0,None,1,3879
4124,02/04/2015,Gariguette,2,4220,0,4124,P,0,None,1,4124
4242,02/04/2015,Gariguette,3,4339,0,4242,P,0,None,1,4242
4310,02/04/2015,Gariguette,4,4408,0,4310,P,0,None,1,4310
4476,02/04/2015,Gariguette,5,4575,0,4476,P,0,None,1,4476
4556,02/04/2015,Gariguette,6,4656,0,4556,P,0,None,1,4556
4653,02/04/2015,Gariguette,7,4754,0,4653,P,0,None,1,4653
4768,02/04/2015,Gariguette,8,4870,0,4768,P,0,None,1,4768
5078,02/04/2015,Gariguette,9,5181,0,5078,P,0,None,1,5078
5182,19/05/2015,Gariguette,1,5286,0,5182,P,0,None,1,5182
5328,19/05/2015,Gariguette,2,5433,0,5328,P,0,None,1,5328
5511,19/05/2015,Gariguette,3,5617,0,5511,P,0,None,1,5511
5654,19/05/2015,Gariguette,4,5761,0,5654,P,0,None,1,5654
5725,19/05/2015,Gariguette,5,5833,0,5725,P,0,None,1,5725
5860,19/05/2015,Gariguette,6,5969,0,5860,P,0,None,1,5860
6054,19/05/2015,Gariguette,7,6164,0,6054,P,0,None,1,6054
6169,19/05/2015,Gariguette,8,6280,0,6169,P,0,None,1,6169
6293,19/05/2015,Gariguette,9,6405,0,6293,P,0,None,1,6293

In [16]:
"""Visualization of One Plante selected according to Genotype, Plante and date"""
"""Capriss	4	10/12/2014
Capriss	7	07/01/2015
Capriss	5	15/02/2015
Capriss	6	02/03/2015
Capriss	6	03/04/2015
Capriss	4	27/05/2015
"""
"""Identification of Vid (Visitor ID)"""
vid = int(df[df.Genotype=='Capriss'][df.Plante==4][df.date=='10-12-2014'].vid)

"""Visualisattion of the Plant"""
scene=Visualization.visualise_plants(g, [vid], positions=[(0,0,0)])
pgl.Viewer.display(scene)

AttributeError: 'DataFrame' object has no attribute 'Plante'

In [17]:
#Visualisation some plants selected according to Genotype and Plante or Genotype and date

#vids = list(df[df.Genotype=='Capriss'][df.Stade==3].vid.values)
vids = list(df[df.Genotype=='Capriss'][df.date=="10-12-2014"].vid.values)
print vids


n = len(vids)
n_cols = 1 #selection of number of column for representation
n_rows = n/n_cols+1

dx =2 #Select start point on x axis on the grid
dy = 4 #Select start point on y axis on the grid
y0 = -n_rows*dx /2.
x0 = -n_cols*dy/2.
positions = [(x0+i*dx, y0+j*dy, 0) for i in range(n_cols) for j in range(n_rows)][:n]

scene = Visualization.visualise_plants(g, vids, positions)
pgl.Viewer.display(scene)

AttributeError: 'DataFrame' object has no attribute 'date'

In [18]:
reload(Rules_production)
reload(Visualization)
import pandas as pd
sel=pd.read_csv('Z:\G1\Marc-Labadie\Python\strawberry\share\data\Plant.selected2.csv', sep=';', skiprows=0, index_col=None)
del sel['dist']
sel.Genotype = sel.Genotype.str.strip() 
#sel = sel[sel.Genotype.str.strip()==('Capris')]
sel_df = pd.merge(sel,df)
sel_df =pd.DataFrame.sort(sel_df,columns= "vid",ascending=True)
#print sel_df

"""Selection of Vids"""
vids= list(sel_df[sel_df.Genotype.isin(["Cir107"])].vid)
print vids
""" Define position"""
n = len(vids)
n_cols = 1 #selection of number of column for representation
n_rows = n/n_cols

dx =3.5 #Select start point on x axis on the grid
dy = 4 #Select start point on y axis on the grid
y0 = -n_rows*dx /2.
x0 = -n_cols*dy/2.
positions = [(x0+i*dx, y0+j*dy, 0) for i in range(n_cols) for j in range(n_rows)][:n]

"""Visualization function"""
scene=Visualization.visualise_plants(g,vids,positions)
pgl.Viewer.display(scene)

IOError: File Z:\G1\Marc-Labadie\Python\strawberry\share\data\Plant.selected2.csv does not exist

In [13]:
sel=pd.read_csv('Z:\G1\Marc-Labadie\Python\strawberry\share\data\Plant.selected2.csv', sep=';', skiprows=0, index_col=None)
del sel['dist']
sel.Genotype = sel.Genotype.str.strip() 
sel_df = pd.merge(sel,df)
sel_df
sel

NameError: name 'pd' is not defined

In [16]:
sel_df = pd.merge(sel,df)
sel_df

Empty DataFrame
Columns: [Genotype, date, Plante, dist, _line, complex, diam_mm, index, label, order, parent, scale, vid]
Index: []

In [22]:
df

,Genotype,Plante,_line,complex,date,diam_mm,index,label,order,parent,scale,vid
1,Capriss,1,47,0,10-12-2014,NaN,1,P,0,None,1,1
118,Capriss,2,167,0,10-12-2014,NaN,118,P,0,None,1,118
209,Capriss,3,260,0,10-12-2014,NaN,209,P,0,None,1,209
263,Capriss,4,315,0,10-12-2014,NaN,263,P,0,None,1,263
340,Capriss,5,394,0,10-12-2014,NaN,340,P,0,None,1,340
434,Capriss,6,490,0,10-12-2014,NaN,434,P,0,None,1,434
522,Capriss,7,579,0,10-12-2014,NaN,522,P,0,None,1,522
602,Capriss,8,660,0,10-12-2014,NaN,602,P,0,None,1,602
667,Capriss,9,726,0,10-12-2014,NaN,667,P,0,None,1,667
752,Capriss,1,813,0,07-01-2015,NaN,752,P,0,None,1,752
833,Capriss,2,895,0,07-01-2015,NaN,833,P,0,None,1,833
954,Capriss,3,1019,0,07-01-2015,NaN,954,P,0,None,1,954
1071,Capriss,4,1138,0,07-01-2015,NaN,1071,P,0,None,1,1071
1244,Capriss,5,1312,0,07-01-2015,NaN,1244,P,0,None,1,1244
1343,Capriss,6,1412,0,07-01-2015,NaN,1343,P,0,None,1,1343
1464,Capriss,7,1534,0,07-01-2015,NaN,1464,P,0,None,1,1464
1583,Capriss,8,1654,0,07-01-2015,NaN,1583,P,0,None,1,1583
1698,Capriss,9,1770,0,07-01-2015,NaN,1698,P,0,None,1,1698
1794,Capriss,1,1867,0,15-02-2015,NaN,1794,P,0,None,1,1794
1913,Capriss,2,1989,0,15-02-2015,NaN,1913,P,0,None,1,1913
2077,Capriss,3,2154,0,15-02-2015,NaN,2077,P,0,None,1,2077
2238,Capriss,4,2316,0,15-02-2015,NaN,2238,P,0,None,1,2238
2314,Capriss,5,2393,0,15-02-2015,NaN,2314,P,0,None,1,2314
2462,Capriss,6,2543,0,15-02-2015,NaN,2462,P,0,None,1,2462
2594,Capriss,7,2677,0,15-02-2015,NaN,2594,P,0,None,1,2594
2673,Capriss,8,2757,0,15-02-2015,NaN,2673,P,0,None,1,2673
2796,Capriss,9,2881,0,15-02-2015,NaN,2796,P,0,None,1,2796
2990,Capriss,1,3076,0,02-03-2015,NaN,2990,P,0,None,1,2990
3118,Capriss,2,3205,0,02-03-2015,NaN,3118,P,0,None,1,3118
3212,Capriss,3,3300,0,02-03-2015,NaN,3212,P,0,None,1,3212
...,...,...,...,...,...,...,...,...,...,...,...,...
33721,Gariguette,7,2674,0,12-02-2015,NaN,33721,P,0,None,1,33721
33796,Gariguette,8,2750,0,12-02-2015,NaN,33796,P,0,None,1,33796
33908,Gariguette,9,2863,0,12-02-2015,NaN,33908,P,0,None,1,33908
34014,Gariguette,1,2970,0,06-03-2015,NaN,34014,P,0,None,1,34014
34105,Gariguette,2,3062,0,06-03-2015,NaN,34105,P,0,None,1,34105
34193,Gariguette,3,3151,0,06-03-2015,NaN,34193,P,0,None,1,34193
34312,Gariguette,4,3271,0,06-03-2015,NaN,34312,P,0,None,1,34312
34442,Gariguette,5,3402,0,06-03-2015,NaN,34442,P,0,None,1,34442
34559,Gariguette,6,3520,0,06-03-2015,NaN,34559,P,0,None,1,34559
34671,Gariguette,7,3633,0,06-03-2015,NaN,34671,P,0,None,1,34671
34745,Gariguette,8,3708,0,06-03-2015,NaN,34745,P,0,None,1,34745
34850,Gariguette,9,3814,0,06-03-2015,NaN,34850,P,0,None,1,34850
34997,Gariguette,1,3962,0,02-04-2015,NaN,34997,P,0,None,1,34997
35242,Gariguette,2,4208,0,02-04-2015,NaN,35242,P,0,None,1,35242
35360,Gariguette,3,4327,0,02-04-2015,NaN,35360,P,0,None,1,35360
35428,Gariguette,4,4396,0,02-04-2015,NaN,35428,P,0,None,1,35428
35593,Gariguette,5,4563,0,02-04-2015,NaN,35593,P,0,None,1,35593
35673,Gariguette,6,4644,0,02-04-2015,NaN,35673,P,0,None,1,35673
35770,Gariguette,7,4742,0,02-04-2015,NaN,35770,P,0,None,1,35770
35885,Gariguette,8,4858,0,02-04-2015,NaN,35885,P,0,None,1,35885
36195,Gariguette,9,5169,0,02-04-2015,NaN,36195,P,0,None,1,36195
36299,Gariguette,1,5274,0,19-05-2015,NaN,36299,P,0,None,1,36299
36442,Gariguette,2,5418,0,19-05-2015,NaN,36442,P,0,None,1,36442
36625,Gariguette,3,5602,0,19-05-2015,NaN,36625,P,0,None,1,36625
36768,Gariguette,4,5746,0,19-05-2015,NaN,36768,P,0,None,1,36768
36839,Gariguette,5,5818,0,19-05-2015,NaN,36839,P,0,None,1,36839
36974,Gariguette,6,5954,0,19-05-2015,NaN,36974,P,0,None,1,36974
37168,Gariguette,7,6149,0,19-05-2015,NaN,37168,P,0,None,1,37168
37283,Gariguette,8,6265,0,19-05-2015,NaN,37283,P,0,None,1,37283
37407,Gariguette,9,6390,0,19-05-2015,NaN,37407,P,0,None,1,37407