# Architecture visualisation

## 0. Module requierement

### 0.1. import standard python modules

In [1]:
from collections import OrderedDict , defaultdict # import OrderedDict and defaultdict function from collections module
import pandas as pd # import pandas module and called pd
import glob # import glob module

### 0.2. import openalea modules

In [2]:
from openalea.core import path # import path function from openalea.core module
from openalea.deploy.shared_data import shared_data # import shared_data function from openalea.deploy.shares_data module
from openalea.mtg import * # import whole functions from openalea.mtg module 
from openalea.mtg.algo import orders # import orders function from openalea.mtg.algo module
from openalea.mtg import stat # import stat function from openalea.mtg module (why we import stat function while above we import openalea.mtg yet)
import openalea.plantgl.all as pgl # import openalea.plantgl.all and called pgl

### 0.3. import strawberry modules

In [3]:
import openalea.strawberry #import openalea.strawberry module

from openalea.strawberry import Rules_production # impoort Rules_production functions from openalea.strawberry module
from openalea.strawberry import Visualization, visualisation2d # import Visualisation and Visualisation2d functions from openalea.strawberry module
from openalea.strawberry import analysis, variables # import analysis and variables functions from openalea.strawberry module
from openalea.strawberry.reader import load_mtg # import load_mtg function from openalea.strawberry.reader

## 1. import Gariguette MTG

Import Gariguette.mtg as g directely from path

In [4]:
g= MTG('c:\\users\\mlabadie\\miniconda2\\envs\\openalea\\lib\\site-packages\\openalea.strawberry-1.0.0-py2.7.egg\\share\\data\\Gariguette.mtg')

## 2. Vizualisations

In [5]:
g.properties()['order'] = orders(g) # add order properties

### 2.1. 3D Visualization

+ 3D vizualisation with leaves (hide_leaves = False)

In [6]:
Visualization.plot3d(g,by=["Sample_date"],hide_leaves=True)

02/04/2015
06/03/2015
08/01/2015
10/12/2014
12/02/2015
19/05/2015

c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:64: Warning: Invalid Color value 7 in setColor (maximum is 6)
  t.setColor(6+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:112: Warning: Invalid Color value 9 in setColor (maximum is 6)
  t.setColor(8+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:64: Warning: Invalid Color value 8 in setColor (maximum is 6)
  t.setColor(6+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:64: Warning: Invalid Color value 9 in setColor (maximum is 6)
  t.setColor(6+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:112: Warning: Invalid Color value 11 in setColor (maximum is 6)
  t.setColor(8+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:112: Warning: Invalid Color value 10 in setColor (maximum is 6)
  t.setColor(8+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:64: Warning: Invalid Color value 10 in setColor (maximum is 6)
  t.setColor(6+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:112: Warning: Invalid Color value 12 in setColor (maximum is 6)
  t.setColor(8+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:127: Warning: Invalid Color value 7 in setColor (maximum is 6)
  t.setColor(2+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:112: Warning: Invalid Color value 8 in setColor (maximum is 6)
  t.setColor(8+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:151: Warning: Invalid Color value 7 in setColor (maximum is 6)
  t.setColor(2+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:64: Warning: Invalid Color value 11 in setColor (maximum is 6)
  t.setColor(6+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:38: Warning: Invalid Color value 7 in setColor (maximum is 6)
  t.setColor(2+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:151: Warning: Invalid Color value 8 in setColor (maximum is 6)
  t.setColor(2+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:64: Warning: Invalid Color value 12 in setColor (maximum is 6)
  t.setColor(6+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:151: Warning: Invalid Color value 9 in setColor (maximum is 6)
  t.setColor(2+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:127: Warning: Invalid Color value 8 in setColor (maximum is 6)
  t.setColor(2+order)
c:\users\mlabadie\miniconda2\envs\openalea\lib\site-packages\openalea.strawberry-1.0.0-py2.7.egg\openalea\strawberry\Rules_production.py:94: Warning: Invalid Color value 7 in setColor (maximum is 6)
  t.setColor(2+order)

+ 3D vizualisation without leaves (hide_leaves==False)

In [47]:
Visualization.plot3d(g,by=["Sample_date"],hide_leaves=False)

02/04/2015
06/03/2015
08/01/2015
10/12/2014
12/02/2015
19/05/2015

## 2.2. 2D visualization

### 2.2.1 2D-Visualization plant by plant

**Commentaires:**  
- Amélioration possible donnée Génotype, date et Plante à la place de g.vertices et le numéros 
- Amélioré l'argument dist pour plus de clarté

In [68]:
visualisation2d.plot2d(g,g.vertices(scale=1)[0:3],dist=[3]*3)

### 2.2.2 visualization of the most central individuals

#### 2.2.2.1 Extraction of the most central individuals

+ Extract MTG data at plant scale (function variable.extract_at_plant_scale)

In [80]:
# Extraction of data at plant scale
df_at_plant_scale = variables.extract_at_plant_scale(g)
# Transform date as date value
df_at_plant_scale.date = pd.to_datetime(df_at_plant_scale.date, dayfirst=True)
df_at_plant_scale

,Genotype,date,modality,plant,nb_total_leaves,nb_total_flowers,nb_stolons,nb_visible_leaves,nb_missing_leaves,nb_vegetative_bud,nb_initiated_bud,nb_floral_bud,nb_inflorescence,leaf_area,order_max,nb_ramifications,vid
0,Gariguette,2014-12-10,A,1,12,0,1,8,0,1,3,7,0,56.33,0,0,1
1,Gariguette,2014-12-10,A,2,12,0,1,8,0,4,3,4,0,55.52,0,0,73
2,Gariguette,2014-12-10,A,3,14,0,2,11,0,3,1,8,0,42.47,0,0,146
3,Gariguette,2014-12-10,A,4,11,0,0,8,0,6,0,5,0,32.84,0,0,263
4,Gariguette,2014-12-10,A,5,10,0,1,6,0,5,2,2,0,48.26,0,0,326
5,Gariguette,2014-12-10,A,6,11,0,1,7,0,3,2,5,0,47.28,0,0,382
6,Gariguette,2014-12-10,A,7,11,0,1,7,0,7,1,2,0,39.71,0,0,444
7,Gariguette,2014-12-10,A,8,9,0,1,6,0,1,3,4,0,65.60,0,0,504
8,Gariguette,2014-12-10,A,9,10,0,1,7,0,4,0,5,0,47.19,0,0,561
9,Gariguette,2015-01-08,A,1,34,0,1,15,0,14,3,13,0,0.00,1,3,635
10,Gariguette,2015-01-08,A,2,15,14,2,11,0,2,2,9,0,55.52,0,0,816
11,Gariguette,2015-01-08,A,3,23,0,0,17,0,10,0,10,1,49.19,1,2,913
12,Gariguette,2015-01-08,A,4,17,22,0,14,0,5,1,10,1,52.30,1,1,1050
13,Gariguette,2015-01-08,A,5,13,20,3,13,0,0,0,9,1,80.35,0,0,1201
14,Gariguette,2015-01-08,A,6,11,18,1,11,0,1,0,9,1,52.30,0,0,1321
15,Gariguette,2015-01-08,A,7,12,17,0,12,0,0,0,12,1,59.89,0,0,1426
16,Gariguette,2015-01-08,A,8,11,19,1,11,0,1,0,9,1,0.00,0,0,1533
17,Gariguette,2015-01-08,A,9,9,24,1,9,0,0,1,7,1,47.84,0,0,1620
18,Gariguette,2015-02-12,A,1,38,41,0,33,0,12,1,19,6,85.55,1,5,1709
19,Gariguette,2015-02-12,A,2,21,30,0,18,0,4,2,9,3,89.21,1,2,1947
20,Gariguette,2015-02-12,A,3,15,42,1,15,0,3,0,9,3,93.65,1,1,2067
21,Gariguette,2015-02-12,A,4,10,32,0,10,0,1,0,8,2,85.55,1,0,2167
22,Gariguette,2015-02-12,A,5,31,33,0,27,0,6,3,16,3,104.85,1,3,2238
23,Gariguette,2015-02-12,A,6,24,43,2,24,0,4,1,14,4,142.62,1,2,2441
24,Gariguette,2015-02-12,A,7,10,21,0,10,0,0,1,8,2,87.73,1,0,2603
25,Gariguette,2015-02-12,A,8,17,31,0,17,0,2,1,11,3,81.71,1,1,2678
26,Gariguette,2015-02-12,A,9,15,30,0,15,0,1,1,11,3,91.12,1,1,2790
27,Gariguette,2015-03-06,A,1,15,29,0,15,0,0,0,11,3,100.99,1,1,2896
28,Gariguette,2015-03-06,A,2,17,38,1,17,0,3,1,7,4,105.06,2,1,2987
29,Gariguette,2015-03-06,A,3,20,42,0,18,0,4,1,11,4,65.60,2,1,3075
30,Gariguette,2015-03-06,A,4,23,27,0,18,0,7,0,12,3,123.73,2,1,3194
31,Gariguette,2015-03-06,A,5,23,39,2,18,0,6,2,9,3,113.99,2,1,3324
32,Gariguette,2015-03-06,A,6,18,36,2,18,0,3,3,8,3,89.73,1,1,3441
33,Gariguette,2015-03-06,A,7,14,31,0,12,0,1,3,6,3,84.26,3,0,3553
34,Gariguette,2015-03-06,A,8,16,42,1,16,0,1,0,10,3,84.47,2,0,3627
35,Gariguette,2015-03-06,A,9,28,36,0,23,0,9,2,12,4,130.59,2,2,3732
36,Gariguette,2015-04-02,A,1,50,78,1,42,0,18,1,15,9,113.00,2,6,3879
37,Gariguette,2015-04-02,A,2,23,55,0,22,0,6,1,9,5,117.72,3,1,4124
38,Gariguette,2015-04-02,A,3,14,34,0,14,0,3,0,8,3,0.00,1,1,4242
39,Gariguette,2015-04-02,A,4,42,55,6,32,0,7,1,12,6,167.66,2,3,4310
40,Gariguette,2015-04-02,A,5,15,43,0,15,0,4,1,5,4,64.42,2,1,4476
41,Gariguette,2015-04-02,A,6,24,49,1,21,0,5,3,3,5,152.90,2,2,4556
42,Gariguette,2015-04-02,A,7,28,50,2,25,0,8,0,8,5,72.76,2,2,4653
43,Gariguette,2015-04-02,A,8,71,75,1,57,0,25,7,14,9,154.91,3,7,4768
44,Gariguette,2015-04-02,A,9,24,31,1,20,0,8,0,7,3,71.58,2,1,5078
45,Gariguette,2015-05-19,A,1,35,52,3,33,0,10,0,7,9,149.47,4,2,5182
46,Gariguette,2015-05-19,A,2,38,67,0,34,0,3,2,13,8,49.64,3,3,5328
47,Gariguette,2015-05-19,A,3,33,51,1,27,0,8,0,10,7,67.96,3,3,5511
48,Gariguette,2015-05-19,A,4,17,33,0,17,0,3,0,5,4,77.18,3,0,5654
49,Gariguette,2015-05-19,A,5,31,62,4,31,0,9,2,7,9,197.84,4,1,5725
50,Gariguette,2015-05-19,A,6,41,76,4,41,0,9,0,14,12,160.45,5,2,5860
51,Gariguette,2015-05-19,A,7,27,51,1,27,0,6,3,6,8,89.41,4,1,6054
52,Gariguette,2015-05-19,A,8,25,46,2,25,0,6,1,6,6,75.25,3,1,6169
53,Gariguette,2015-05-19,A,9,47,90,6,47,0,15,2,9,13,137.41,4,5,6293

+ Function to calculate the most central individuals

In [82]:
# Function to select the most central individual with all variable 
df_individuals = analysis.median_individuals(df_at_plant_scale)
df_individuals

,Genotype,date,modality,plant,nb_total_leaves,nb_total_flowers,nb_stolons,nb_visible_leaves,nb_missing_leaves,nb_vegetative_bud,nb_initiated_bud,nb_floral_bud,nb_inflorescence,leaf_area,order_max,nb_ramifications,vid
5,Gariguette,2014-12-10,A,6,11,0,1,7,0,3,2,5,0,47.28,0,0,382
14,Gariguette,2015-01-08,A,6,11,18,1,11,0,1,0,9,1,52.30,0,0,1321
25,Gariguette,2015-02-12,A,8,17,31,0,17,0,2,1,11,3,81.71,1,1,2678
28,Gariguette,2015-03-06,A,2,17,38,1,17,0,3,1,7,4,105.06,2,1,2987
42,Gariguette,2015-04-02,A,7,28,50,2,25,0,8,0,8,5,72.76,2,2,4653
45,Gariguette,2015-05-19,A,1,35,52,3,33,0,10,0,7,9,149.47,4,2,5182

+ visualization of spatio-temporal developement using 2D visualisation

In [84]:
# selection of vid of median individuals
pids = list(df_individuals.vid)
n = len(pids)

# Plot 2D- visualisation of the most central plant
visualisation2d.plot2d(g, pids, dist=[6]*n)

,Genotype,date,modality,plant,order,nb_visible_leaves,nb_foliar_primordia,nb_total_leaves,nb_open_flowers,nb_aborted_flowers,nb_total_flowers,nb_vegetative_bud,nb_initiated_bud,nb_floral_bud,nb_stolons,type_of_crown,crown_status,vid,plant_vid
0,Gariguette,02/04/2015,A,9,1,2,0,2,6,0,6,1,0,0,0,3,4,5120,5078
1,Gariguette,02/04/2015,A,6,2,2,3,5,0,0,0,3,0,1,0,3,3,4609,4556
2,Gariguette,10/12/2014,A,1,0,8,4,12,0,0,0,1,3,7,1,1,3,2,1
3,Gariguette,06/03/2015,A,3,0,10,0,10,17,0,19,0,0,8,0,1,4,3076,3075
4,Gariguette,02/04/2015,A,9,2,2,2,4,0,0,0,2,0,1,0,2,3,5125,5078
5,Gariguette,19/05/2015,A,7,4,3,0,3,0,0,5,2,0,0,1,2,4,6151,6054
6,Gariguette,06/03/2015,A,7,2,3,0,3,2,0,8,0,1,0,0,2,4,3595,3553
7,Gariguette,12/02/2015,A,6,1,3,0,3,0,0,12,1,1,1,0,2,4,2574,2441
8,Gariguette,02/04/2015,A,1,1,3,0,3,9,0,9,1,0,0,0,2,4,4075,3879
9,Gariguette,19/05/2015,A,6,5,3,0,3,4,0,7,1,0,0,2,2,4,5976,5860
10,Gariguette,02/04/2015,A,6,2,3,0,3,1,0,7,1,1,1,0,2,4,4627,4556
11,Gariguette,12/02/2015,A,3,0,9,0,9,3,0,22,0,0,6,1,1,4,2068,2067
12,Gariguette,06/03/2015,A,7,3,1,2,3,0,0,0,1,1,1,0,2,3,3605,3553
13,Gariguette,02/04/2015,A,8,2,3,0,3,0,0,7,2,0,1,0,2,4,4953,4768
14,Gariguette,19/05/2015,A,4,2,3,0,3,0,0,0,1,0,1,0,2,4,5695,5654
15,Gariguette,19/05/2015,A,8,0,9,0,9,23,0,23,1,0,1,0,1,4,6170,6169
16,Gariguette,08/01/2015,A,4,0,11,0,11,0,0,22,0,0,10,0,1,4,1051,1050
17,Gariguette,08/01/2015,A,4,1,3,3,6,0,0,0,5,1,0,0,3,3,1053,1050
18,Gariguette,19/05/2015,A,6,4,3,0,3,6,0,7,2,0,0,0,2,4,5968,5860
19,Gariguette,12/02/2015,A,3,1,3,0,3,0,0,11,1,0,2,0,2,4,2139,2067
20,Gariguette,02/04/2015,A,9,2,3,2,5,0,0,0,4,0,1,0,2,3,5159,5078
21,Gariguette,12/02/2015,A,7,0,8,0,8,0,0,15,0,0,7,0,1,4,2604,2603
22,Gariguette,19/05/2015,A,1,3,3,0,3,0,0,0,1,0,0,0,2,4,5298,5182
23,Gariguette,02/04/2015,A,7,0,11,0,11,23,0,23,0,0,4,2,1,4,4654,4653
24,Gariguette,02/04/2015,A,7,1,4,0,4,2,0,4,2,0,0,0,3,4,4656,4653
25,Gariguette,10/12/2014,A,9,0,7,3,10,0,0,0,4,0,5,1,1,3,562,561
26,Gariguette,06/03/2015,A,3,1,2,0,2,2,0,8,1,0,0,0,3,4,3129,3075
27,Gariguette,19/05/2015,A,4,1,2,0,2,6,0,6,1,0,0,0,2,4,5690,5654
28,Gariguette,02/04/2015,A,7,2,1,2,3,0,0,0,2,0,0,0,2,3,4667,4653
29,Gariguette,19/05/2015,A,9,1,2,0,2,10,0,10,0,0,1,0,3,4,6344,6293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,Gariguette,02/04/2015,A,8,2,2,0,2,10,0,11,1,0,0,0,2,4,5055,4768
212,Gariguette,06/03/2015,A,6,1,3,0,3,3,0,8,1,1,1,0,2,4,3520,3441
213,Gariguette,19/05/2015,A,7,1,3,0,3,5,0,5,1,0,1,0,3,4,6082,6054
214,Gariguette,02/04/2015,A,8,3,2,1,3,0,0,0,1,0,1,0,2,3,5060,4768
215,Gariguette,02/04/2015,A,1,2,5,0,5,0,0,0,3,1,1,0,2,4,4043,3879
216,Gariguette,19/05/2015,A,7,2,3,0,3,4,0,4,1,1,0,0,2,4,6092,6054
217,Gariguette,06/03/2015,A,2,1,3,0,3,0,0,7,1,0,2,0,3,4,3021,2987
218,Gariguette,08/01/2015,A,3,1,2,4,6,0,0,0,5,0,1,0,3,3,980,913
219,Gariguette,19/05/2015,A,7,3,2,0,2,0,0,5,1,0,1,0,2,4,6102,6054
220,Gariguette,02/04/2015,A,9,0,11,0,11,18,0,18,1,0,4,1,1,4,5079,5078
221,Gariguette,19/05/2015,A,2,1,3,0,3,0,0,9,0,1,1,0,2,4,5455,5328
222,Gariguette,12/02/2015,A,2,1,3,0,3,0,0,0,1,0,1,0,3,4,2017,1947
223,Gariguette,06/03/2015,A,7,0,3,0,3,0,0,0,0,0,2,0,1,4,3554,3553
224,Gariguette,19/05/2015,A,3,1,2,0,2,6,0,8,0,0,0,0,2,4,5604,5511
225,Gariguette,19/05/2015,A,3,2,4,0,4,0,0,2,3,0,0,0,3,4,5606,5511
226,Gariguette,06/03/2015,A,5,1,2,0,2,7,0,10,0,0,1,0,2,4,3409,3324
227,Gariguette,19/05/2015,A,7,1,2,0,2,8,0,9,0,0,1,0,2,4,6120,6054
228,Gariguette,06/03/2015,A,2,1,2,0,2,3,0,7,0,0,1,0,2,4,3051,2987
229,Gariguette,02/04/2015,A,6,1,2,0,2,8,0,8,0,0,0,0,3,4,4588,4556
230,Gariguette,02/04/2015,A,6,2,2,0,2,1,0,6,1,0,1,0,2,4,4593,4556
231,Gariguette,06/03/2015,A,7,1,5,0,5,20,0,23,0,1,3,0,2,4,3570,3553
232,Gariguette,12/02/2015,A,6,1,3,0,3,0,0,14,2,0,1,0,3,4,2547,2441
233,Gariguette,02/04/2015,A,1,2,3,0,3,2,0,9,0,0,3,0,2,4,4094,3879
234,Gariguette,12/02/2015,A,2,1,3,0,3,0,0,8,1,1,1,0,2,4,2038,1947
235,Gariguette,19/05/2015,A,9,3,3,0,3,5,0,5,1,0,0,1,2,4,6481,6293
236,Gariguette,10/12/2014,A,8,0,6,3,9,0,0,0,1,3,4,1,1,3,505,504
237,Gariguette,19/05/2015,A,3,2,4,0,4,14,0,14,1,0,2,0,2,4,5628,5511
238,Gariguette,19/05/2015,A,7,3,3,0,3,4,0,5,1,0,1,0,2,4,6141,6054
239,Gariguette,08/01/2015,A,8,0,11,0,11,0,0,19,1,0,9,1,1,4,1534,1533
240,Gariguette,02/04/2015,A,6,1,2,0,2,7,0,7,0,0,0,0,2,4,4607,4556